language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t simple-express .
  - docker tag simple-express mvrkrishna/simple-express:latest

after_success:
  - echo "Ishaan@123" | docker login -u "mvrkrishna" --password-stdin
  - docker push mvrkrishna/simple-express
